name: Docker build

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build + Push Kaldi image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo.
      uses: actions/checkout@v2
    - name: Set up QEMU.
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx.
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub.
      uses: docker/login-action@v1.10.0
      with:
        username: ilshidur
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push.
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./docker
        file: Dockerfile.kaldi-fr
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: kaldi-fr:latest
    - name: Discord notif. error
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Error deploying : https://github.com/${{github.repository}}. For more informations, see https://github.com/${{github.repository}}/actions.'
